/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskResultsRouteImport } from './routes/task-results'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as KpisRouteImport } from './routes/kpis'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistsIdRouteImport } from './routes/checklists.$id'

const TaskResultsRoute = TaskResultsRouteImport.update({
  id: '/task-results',
  path: '/task-results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisRoute = KpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsIdRoute = ChecklistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChecklistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/checklists': typeof ChecklistsRouteWithChildren
  '/kpis': typeof KpisRoute
  '/settings': typeof SettingsRoute
  '/task-results': typeof TaskResultsRoute
  '/checklists/$id': typeof ChecklistsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/checklists': typeof ChecklistsRouteWithChildren
  '/kpis': typeof KpisRoute
  '/settings': typeof SettingsRoute
  '/task-results': typeof TaskResultsRoute
  '/checklists/$id': typeof ChecklistsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/checklists': typeof ChecklistsRouteWithChildren
  '/kpis': typeof KpisRoute
  '/settings': typeof SettingsRoute
  '/task-results': typeof TaskResultsRoute
  '/checklists/$id': typeof ChecklistsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/checklists'
    | '/kpis'
    | '/settings'
    | '/task-results'
    | '/checklists/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/checklists'
    | '/kpis'
    | '/settings'
    | '/task-results'
    | '/checklists/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/checklists'
    | '/kpis'
    | '/settings'
    | '/task-results'
    | '/checklists/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ChecklistsRoute: typeof ChecklistsRouteWithChildren
  KpisRoute: typeof KpisRoute
  SettingsRoute: typeof SettingsRoute
  TaskResultsRoute: typeof TaskResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/task-results': {
      id: '/task-results'
      path: '/task-results'
      fullPath: '/task-results'
      preLoaderRoute: typeof TaskResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis': {
      id: '/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof KpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/$id': {
      id: '/checklists/$id'
      path: '/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof ChecklistsIdRouteImport
      parentRoute: typeof ChecklistsRoute
    }
  }
}

interface ChecklistsRouteChildren {
  ChecklistsIdRoute: typeof ChecklistsIdRoute
}

const ChecklistsRouteChildren: ChecklistsRouteChildren = {
  ChecklistsIdRoute: ChecklistsIdRoute,
}

const ChecklistsRouteWithChildren = ChecklistsRoute._addFileChildren(
  ChecklistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ChecklistsRoute: ChecklistsRouteWithChildren,
  KpisRoute: KpisRoute,
  SettingsRoute: SettingsRoute,
  TaskResultsRoute: TaskResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
