/**
 * Seed configuration — mapping from domain concepts to CDF externalIds and spaces.
 * This is the "Rosetta Stone" between the seed design and the actual CDF structure.
 */
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';

const __dir = dirname(fileURLToPath(import.meta.url));

function loadJson(rel) {
  return JSON.parse(readFileSync(resolve(__dir, rel), 'utf8'));
}

export const PERSONAS        = loadJson('./data/personas.json');
export const ROUTES_EXTRA    = loadJson('./data/routes-extra.json');
export const EVENTS_CALENDAR = loadJson('./data/events-calendar.json');

// Excel-sourced routes (Routes 1–4 extracted from A Line OEC Routes 2 (1).xlsx)
// These slugs match what we use in externalIds
export const ROUTES_EXCEL = [
  {
    slug: 'route1',
    title: 'Route 1 — Kraft Digester & Washing',
    section: '7F',
    equipmentCount: 99,
    // Key equipment slugs (subset — full list generated by assets.mjs from excel-raw-extract.json)
    keyEquipments: [
      'diffuser-scraper', 'north-filtrate-pump', 'south-filtrate-pump',
      'chip-feeder-hp', 'chip-feeder-lp', 'blow-tank-agitator',
    ],
  },
  {
    slug: 'route2',
    title: 'Route 2 — Chip & Liquor Feed',
    section: '2F',
    equipmentCount: 45,
    keyEquipments: ['chip-feeder-lp', 'chip-feeder-hp', 'chip-meter', 'steaming-vessel'],
  },
  {
    slug: 'route3',
    title: 'Route 3 — Brown Stock Washing',
    section: '3F',
    equipmentCount: 38,
    keyEquipments: ['washer-1-drive', 'washer-2-drive', 'washer-3-drive', 'filtrate-pump-a'],
  },
  {
    slug: 'route4',
    title: 'Route 4 — Pulp Screening & Cleaning',
    section: '4F',
    equipmentCount: 38,
    keyEquipments: ['pressure-screen-a', 'pressure-screen-b', 'centri-cleaner-a'],
  },
];

export const ALL_ROUTES = [
  ...ROUTES_EXCEL,
  ...ROUTES_EXTRA,
];

// Shifts (must match InspectionShift SST externalIds: CKM_SHIFT_GR1_*)
export const SHIFTS = [
  { code: 'D', name: 'Day Shift',       startHour: 6,  endHour: 14 },
  { code: 'A', name: 'Afternoon Shift', startHour: 14, endHour: 22 },
  { code: 'N', name: 'Night Shift',     startHour: 22, endHour: 6  },
];

// Supervisor lookup by shift
export const SUPERVISORS = {
  D: 'sup.david.nguyen',
  A: 'sup.carol.bishop',
  N: 'sup.david.nguyen', // night shift also covered by David on-call
};

// Measurement type thresholds for standard measurements (default if not route-specific)
export const MEASUREMENT_DEFAULTS = {
  'IB-BEARING-TEMP':     { unit: '°F', min: 70,   max: 180,  threshold: 175, typical: 140, stddev: 12 },
  'OB-BEARING-TEMP':     { unit: '°F', min: 70,   max: 180,  threshold: 175, typical: 138, stddev: 14 },
  'MOTOR-TEMP':          { unit: '°F', min: 60,   max: 195,  threshold: 190, typical: 155, stddev: 15 },
  'IB-VIBRATION-IPS':    { unit: 'ips', min: 0.0,  max: 0.4,  threshold: 0.35, typical: 0.08, stddev: 0.04 },
  'OB-VIBRATION-IPS':    { unit: 'ips', min: 0.0,  max: 0.4,  threshold: 0.35, typical: 0.09, stddev: 0.04 },
  'MOTOR-AMPS':          { unit: 'A',  min: 5,    max: 150,  threshold: 145, typical: 65,  stddev: 12 },
  'SEAL-PRESSURE-PSI':   { unit: 'PSI', min: 10,   max: 80,   threshold: 75,  typical: 45,  stddev: 8 },
  'INLET-PRESSURE-PSI':  { unit: 'PSI', min: 5,    max: 100,  threshold: 95,  typical: 55,  stddev: 10 },
  'OUTLET-PRESSURE-PSI': { unit: 'PSI', min: 5,    max: 150,  threshold: 145, typical: 85,  stddev: 12 },
  'FLOW-GPM':            { unit: 'GPM', min: 50,   max: 2000, threshold: 1900, typical: 800, stddev: 100 },
  'SPEED-RPM':           { unit: 'RPM', min: 1200, max: 3600, threshold: 3500, typical: 1800, stddev: 100 },
  'GAP-MM':              { unit: 'mm', min: 0.5,  max: 10.0, threshold: 9.0,  typical: 4.5, stddev: 0.8 },
  'LEVEL-PERCENT':       { unit: '%',  min: 10,   max: 95,   threshold: 90,   typical: 55,  stddev: 10 },
  'TEMP-DEGF':           { unit: '°F', min: 100,  max: 300,  threshold: 290,  typical: 200, stddev: 20 },
  'INLET-TEMP-DEGF':     { unit: '°F', min: 100,  max: 300,  threshold: 290,  typical: 195, stddev: 18 },
  'OUTLET-TEMP-DEGF':    { unit: '°F', min: 80,   max: 280,  threshold: 275,  typical: 170, stddev: 15 },
  'STEAM-PRESSURE-PSI':  { unit: 'PSI', min: 10,   max: 50,   threshold: 48,   typical: 28,  stddev: 5 },
  'CASING-TEMP':         { unit: '°F', min: 80,   max: 200,  threshold: 195,  typical: 130, stddev: 18 },
  'DP-PSI':              { unit: 'PSI', min: 1,    max: 30,   threshold: 28,   typical: 10,  stddev: 3 },
  'DISCHARGE-PRESSURE-PSI': { unit: 'PSI', min: 80, max: 150, threshold: 145,  typical: 100, stddev: 8 },
};

/** Get the persona assigned to a route+shift */
export function getPersona(routeSlug, shiftCode) {
  const ops = PERSONAS.filter(p => !p.isSupervisor);
  // Find persona whose preferred route and shift match
  const match = ops.find(p => p.shift === shiftCode && p.routes.includes(routeSlug));
  // Fallback: any operator of that shift
  return match ?? ops.find(p => p.shift === shiftCode) ?? ops[0];
}
